SELECT
    invoice_number,
    invoice_date,
    customer_name,
    document_currency,
    freight_charges,
    invoice_quantity AS sales_quantity,
    sales_unit,
    unit,
    requested_quantity,
    net_value,
    unit_price,
    tax_amount,
    total_amount,
    shipping_term_details,
    material_description,
    payment_term_description,
    baseline_date,
    payment_date,
    payment_days,
    amount_paid,
    outstanding_amount,
    payment_status,
    material_group,
    dateDiff('day', baseline_date, payment_date) AS delay_days
FROM manufacturing.analytics
where invoice_date >= '2023-01-01';